// ---------------------------------------------------------------------------
// Paises ISO 3166-1 alpha-2 -- Datos estaticos para ENFOQUE 365
// Nombres en espanol sin acentos ni emojis (ASCII puro).
// Los paises prioritarios aparecen primero en el orden indicado,
// el resto se ordena alfabeticamente por nombre.
// ---------------------------------------------------------------------------

export interface Country {
  code: string;
  name: string;
  tax_label: string;
}

export const COUNTRIES: Country[] = [
  // ---- Paises prioritarios (orden fijo) ------------------------------------
  { code: 'DO', name: 'Republica Dominicana', tax_label: 'RNC' },
  { code: 'US', name: 'Estados Unidos', tax_label: 'EIN' },
  { code: 'CO', name: 'Colombia', tax_label: 'NIT' },
  { code: 'MX', name: 'Mexico', tax_label: 'RFC' },
  { code: 'AR', name: 'Argentina', tax_label: 'CUIT' },
  { code: 'CL', name: 'Chile', tax_label: 'RUT' },
  { code: 'PE', name: 'Peru', tax_label: 'RUC' },
  { code: 'EC', name: 'Ecuador', tax_label: 'RUC' },
  { code: 'PA', name: 'Panama', tax_label: 'RUC' },
  { code: 'BR', name: 'Brasil', tax_label: 'CNPJ' },
  { code: 'ES', name: 'Espana', tax_label: 'NIF' },
  { code: 'GT', name: 'Guatemala', tax_label: 'NIT' },
  { code: 'HN', name: 'Honduras', tax_label: 'RTN' },
  { code: 'SV', name: 'El Salvador', tax_label: 'NIT' },
  { code: 'CR', name: 'Costa Rica', tax_label: 'NITE' },
  { code: 'NI', name: 'Nicaragua', tax_label: 'RUC' },
  { code: 'UY', name: 'Uruguay', tax_label: 'RUT' },
  { code: 'PY', name: 'Paraguay', tax_label: 'RUC' },
  { code: 'BO', name: 'Bolivia', tax_label: 'NIT' },
  { code: 'VE', name: 'Venezuela', tax_label: 'RIF' },
  { code: 'CU', name: 'Cuba', tax_label: 'Tax ID' },
  { code: 'PR', name: 'Puerto Rico', tax_label: 'EIN' },

  // ---- Resto del mundo (orden alfabetico por nombre en espanol) ------------
  { code: 'AF', name: 'Afganistan', tax_label: 'TIN' },
  { code: 'AL', name: 'Albania', tax_label: 'NIPT' },
  { code: 'DE', name: 'Alemania', tax_label: 'Steuernummer' },
  { code: 'AD', name: 'Andorra', tax_label: 'NRT' },
  { code: 'AO', name: 'Angola', tax_label: 'NIF' },
  { code: 'AG', name: 'Antigua y Barbuda', tax_label: 'TIN' },
  { code: 'SA', name: 'Arabia Saudita', tax_label: 'Tax ID' },
  { code: 'DZ', name: 'Argelia', tax_label: 'NIF' },
  { code: 'AM', name: 'Armenia', tax_label: 'TIN' },
  { code: 'AU', name: 'Australia', tax_label: 'ABN' },
  { code: 'AT', name: 'Austria', tax_label: 'UID' },
  { code: 'AZ', name: 'Azerbaiyan', tax_label: 'TIN' },
  { code: 'BS', name: 'Bahamas', tax_label: 'TIN' },
  { code: 'BD', name: 'Bangladesh', tax_label: 'TIN' },
  { code: 'BB', name: 'Barbados', tax_label: 'TIN' },
  { code: 'BH', name: 'Barein', tax_label: 'Tax ID' },
  { code: 'BY', name: 'Bielorrusia', tax_label: 'UNP' },
  { code: 'BE', name: 'Belgica', tax_label: 'BTW' },
  { code: 'BZ', name: 'Belice', tax_label: 'TIN' },
  { code: 'BJ', name: 'Benin', tax_label: 'IFU' },
  { code: 'BM', name: 'Bermudas', tax_label: 'Tax ID' },
  { code: 'BT', name: 'Butan', tax_label: 'TIN' },
  { code: 'BA', name: 'Bosnia y Herzegovina', tax_label: 'ID' },
  { code: 'BW', name: 'Botsuana', tax_label: 'TIN' },
  { code: 'BN', name: 'Brunei Darussalam', tax_label: 'Tax ID' },
  { code: 'BG', name: 'Bulgaria', tax_label: 'EIK' },
  { code: 'BF', name: 'Burkina Faso', tax_label: 'IFU' },
  { code: 'BI', name: 'Burundi', tax_label: 'NIF' },
  { code: 'CV', name: 'Cabo Verde', tax_label: 'NIF' },
  { code: 'KH', name: 'Camboya', tax_label: 'TIN' },
  { code: 'CM', name: 'Camerun', tax_label: 'NIU' },
  { code: 'CA', name: 'Canada', tax_label: 'BN' },
  { code: 'QA', name: 'Catar', tax_label: 'Tax ID' },
  { code: 'TD', name: 'Chad', tax_label: 'NIF' },
  { code: 'CZ', name: 'Chequia', tax_label: 'ICO' },
  { code: 'CN', name: 'China', tax_label: 'USCC' },
  { code: 'CY', name: 'Chipre', tax_label: 'TIC' },
  { code: 'VA', name: 'Ciudad del Vaticano', tax_label: 'Tax ID' },
  { code: 'KM', name: 'Comoras', tax_label: 'NIF' },
  { code: 'CG', name: 'Congo', tax_label: 'NIF' },
  { code: 'CD', name: 'Congo (Republica Democratica)', tax_label: 'NIF' },
  { code: 'KP', name: 'Corea del Norte', tax_label: 'Tax ID' },
  { code: 'KR', name: 'Corea del Sur', tax_label: 'BRN' },
  { code: 'CI', name: 'Costa de Marfil', tax_label: 'NCC' },
  { code: 'HR', name: 'Croacia', tax_label: 'OIB' },
  { code: 'DK', name: 'Dinamarca', tax_label: 'CVR' },
  { code: 'DM', name: 'Dominica', tax_label: 'TIN' },
  { code: 'EG', name: 'Egipto', tax_label: 'TIN' },
  { code: 'AE', name: 'Emiratos Arabes Unidos', tax_label: 'TRN' },
  { code: 'ER', name: 'Eritrea', tax_label: 'TIN' },
  { code: 'SK', name: 'Eslovaquia', tax_label: 'ICO' },
  { code: 'SI', name: 'Eslovenia', tax_label: 'DDV' },
  { code: 'EE', name: 'Estonia', tax_label: 'KMKR' },
  { code: 'SZ', name: 'Esuatini', tax_label: 'TIN' },
  { code: 'ET', name: 'Etiopia', tax_label: 'TIN' },
  { code: 'PH', name: 'Filipinas', tax_label: 'TIN' },
  { code: 'FI', name: 'Finlandia', tax_label: 'Y-tunnus' },
  { code: 'FJ', name: 'Fiyi', tax_label: 'TIN' },
  { code: 'FR', name: 'Francia', tax_label: 'SIRET' },
  { code: 'GA', name: 'Gabon', tax_label: 'NIF' },
  { code: 'GM', name: 'Gambia', tax_label: 'TIN' },
  { code: 'GE', name: 'Georgia', tax_label: 'TIN' },
  { code: 'GH', name: 'Ghana', tax_label: 'TIN' },
  { code: 'GD', name: 'Granada', tax_label: 'TIN' },
  { code: 'GR', name: 'Grecia', tax_label: 'AFM' },
  { code: 'GL', name: 'Groenlandia', tax_label: 'Tax ID' },
  { code: 'GP', name: 'Guadalupe', tax_label: 'SIRET' },
  { code: 'GU', name: 'Guam', tax_label: 'EIN' },
  { code: 'GY', name: 'Guyana', tax_label: 'TIN' },
  { code: 'GF', name: 'Guayana Francesa', tax_label: 'SIRET' },
  { code: 'GN', name: 'Guinea', tax_label: 'NIF' },
  { code: 'GQ', name: 'Guinea Ecuatorial', tax_label: 'NIF' },
  { code: 'GW', name: 'Guinea-Bisau', tax_label: 'NIF' },
  { code: 'HT', name: 'Haiti', tax_label: 'NIF' },
  { code: 'HU', name: 'Hungria', tax_label: 'Tax ID' },
  { code: 'IN', name: 'India', tax_label: 'GSTIN' },
  { code: 'ID', name: 'Indonesia', tax_label: 'NPWP' },
  { code: 'IQ', name: 'Irak', tax_label: 'Tax ID' },
  { code: 'IR', name: 'Iran', tax_label: 'Tax ID' },
  { code: 'IE', name: 'Irlanda', tax_label: 'VAT' },
  { code: 'IS', name: 'Islandia', tax_label: 'VSK' },
  { code: 'MH', name: 'Islas Marshall', tax_label: 'EIN' },
  { code: 'SB', name: 'Islas Salomon', tax_label: 'TIN' },
  { code: 'IL', name: 'Israel', tax_label: 'Tax ID' },
  { code: 'IT', name: 'Italia', tax_label: 'P.IVA' },
  { code: 'JM', name: 'Jamaica', tax_label: 'TRN' },
  { code: 'JP', name: 'Japon', tax_label: 'Tax ID' },
  { code: 'JO', name: 'Jordania', tax_label: 'TIN' },
  { code: 'KZ', name: 'Kazajistan', tax_label: 'BIN' },
  { code: 'KE', name: 'Kenia', tax_label: 'PIN' },
  { code: 'KG', name: 'Kirguistan', tax_label: 'INN' },
  { code: 'KI', name: 'Kiribati', tax_label: 'TIN' },
  { code: 'KW', name: 'Kuwait', tax_label: 'Tax ID' },
  { code: 'LA', name: 'Laos', tax_label: 'TIN' },
  { code: 'LS', name: 'Lesoto', tax_label: 'TIN' },
  { code: 'LV', name: 'Letonia', tax_label: 'PVN' },
  { code: 'LB', name: 'Libano', tax_label: 'TIN' },
  { code: 'LR', name: 'Liberia', tax_label: 'TIN' },
  { code: 'LY', name: 'Libia', tax_label: 'TIN' },
  { code: 'LI', name: 'Liechtenstein', tax_label: 'Tax ID' },
  { code: 'LT', name: 'Lituania', tax_label: 'PVM' },
  { code: 'LU', name: 'Luxemburgo', tax_label: 'TVA' },
  { code: 'MK', name: 'Macedonia del Norte', tax_label: 'EDB' },
  { code: 'MG', name: 'Madagascar', tax_label: 'NIF' },
  { code: 'MY', name: 'Malasia', tax_label: 'TIN' },
  { code: 'MW', name: 'Malaui', tax_label: 'TPIN' },
  { code: 'MV', name: 'Maldivas', tax_label: 'TIN' },
  { code: 'ML', name: 'Mali', tax_label: 'NIF' },
  { code: 'MT', name: 'Malta', tax_label: 'VAT' },
  { code: 'MA', name: 'Marruecos', tax_label: 'ICE' },
  { code: 'MQ', name: 'Martinica', tax_label: 'SIRET' },
  { code: 'MU', name: 'Mauricio', tax_label: 'BRN' },
  { code: 'MR', name: 'Mauritania', tax_label: 'NIF' },
  { code: 'YT', name: 'Mayotte', tax_label: 'SIRET' },
  { code: 'FM', name: 'Micronesia', tax_label: 'TIN' },
  { code: 'MD', name: 'Moldavia', tax_label: 'IDNO' },
  { code: 'MC', name: 'Monaco', tax_label: 'NIS' },
  { code: 'MN', name: 'Mongolia', tax_label: 'TIN' },
  { code: 'ME', name: 'Montenegro', tax_label: 'PIB' },
  { code: 'MS', name: 'Montserrat', tax_label: 'TIN' },
  { code: 'MZ', name: 'Mozambique', tax_label: 'NUIT' },
  { code: 'MM', name: 'Myanmar', tax_label: 'TIN' },
  { code: 'NA', name: 'Namibia', tax_label: 'TIN' },
  { code: 'NR', name: 'Nauru', tax_label: 'Tax ID' },
  { code: 'NP', name: 'Nepal', tax_label: 'PAN' },
  { code: 'NE', name: 'Niger', tax_label: 'NIF' },
  { code: 'NG', name: 'Nigeria', tax_label: 'TIN' },
  { code: 'NO', name: 'Noruega', tax_label: 'Org.nr' },
  { code: 'NC', name: 'Nueva Caledonia', tax_label: 'RIDET' },
  { code: 'NZ', name: 'Nueva Zelanda', tax_label: 'NZBN' },
  { code: 'OM', name: 'Oman', tax_label: 'Tax ID' },
  { code: 'NL', name: 'Paises Bajos', tax_label: 'BTW' },
  { code: 'PK', name: 'Pakistan', tax_label: 'NTN' },
  { code: 'PW', name: 'Palaos', tax_label: 'TIN' },
  { code: 'PS', name: 'Palestina', tax_label: 'TIN' },
  { code: 'PG', name: 'Papua Nueva Guinea', tax_label: 'TIN' },
  { code: 'PL', name: 'Polonia', tax_label: 'NIP' },
  { code: 'PT', name: 'Portugal', tax_label: 'NIF' },
  { code: 'GB', name: 'Reino Unido', tax_label: 'UTR' },
  { code: 'CF', name: 'Republica Centroafricana', tax_label: 'NIF' },
  { code: 'RE', name: 'Reunion', tax_label: 'SIRET' },
  { code: 'RW', name: 'Ruanda', tax_label: 'TIN' },
  { code: 'RO', name: 'Rumania', tax_label: 'CUI' },
  { code: 'RU', name: 'Rusia', tax_label: 'INN' },
  { code: 'WS', name: 'Samoa', tax_label: 'TIN' },
  { code: 'AS', name: 'Samoa Americana', tax_label: 'EIN' },
  { code: 'BL', name: 'San Bartolome', tax_label: 'Tax ID' },
  { code: 'KN', name: 'San Cristobal y Nieves', tax_label: 'TIN' },
  { code: 'SM', name: 'San Marino', tax_label: 'COE' },
  { code: 'MF', name: 'San Martin (parte francesa)', tax_label: 'Tax ID' },
  { code: 'SX', name: 'San Martin (parte neerlandesa)', tax_label: 'Tax ID' },
  { code: 'PM', name: 'San Pedro y Miquelon', tax_label: 'Tax ID' },
  { code: 'VC', name: 'San Vicente y las Granadinas', tax_label: 'TIN' },
  { code: 'LC', name: 'Santa Lucia', tax_label: 'TIN' },
  { code: 'ST', name: 'Santo Tome y Principe', tax_label: 'NIF' },
  { code: 'SN', name: 'Senegal', tax_label: 'NINEA' },
  { code: 'RS', name: 'Serbia', tax_label: 'PIB' },
  { code: 'SC', name: 'Seychelles', tax_label: 'TIN' },
  { code: 'SL', name: 'Sierra Leona', tax_label: 'TIN' },
  { code: 'SG', name: 'Singapur', tax_label: 'UEN' },
  { code: 'SY', name: 'Siria', tax_label: 'Tax ID' },
  { code: 'SO', name: 'Somalia', tax_label: 'TIN' },
  { code: 'LK', name: 'Sri Lanka', tax_label: 'TIN' },
  { code: 'ZA', name: 'Sudafrica', tax_label: 'Tax ID' },
  { code: 'SD', name: 'Sudan', tax_label: 'TIN' },
  { code: 'SS', name: 'Sudan del Sur', tax_label: 'TIN' },
  { code: 'SE', name: 'Suecia', tax_label: 'Org.nr' },
  { code: 'CH', name: 'Suiza', tax_label: 'UID' },
  { code: 'SR', name: 'Surinam', tax_label: 'TIN' },
  { code: 'TH', name: 'Tailandia', tax_label: 'TIN' },
  { code: 'TW', name: 'Taiwan', tax_label: 'Tax ID' },
  { code: 'TZ', name: 'Tanzania', tax_label: 'TIN' },
  { code: 'TJ', name: 'Tayikistan', tax_label: 'TIN' },
  { code: 'IO', name: 'Territorio Britanico del Oceano Indico', tax_label: 'Tax ID' },
  { code: 'TF', name: 'Territorios Australes Franceses', tax_label: 'Tax ID' },
  { code: 'TL', name: 'Timor Oriental', tax_label: 'TIN' },
  { code: 'TG', name: 'Togo', tax_label: 'NIF' },
  { code: 'TK', name: 'Tokelau', tax_label: 'Tax ID' },
  { code: 'TO', name: 'Tonga', tax_label: 'TIN' },
  { code: 'TT', name: 'Trinidad y Tobago', tax_label: 'BIR' },
  { code: 'TN', name: 'Tunez', tax_label: 'MF' },
  { code: 'TM', name: 'Turkmenistan', tax_label: 'TIN' },
  { code: 'TR', name: 'Turquia', tax_label: 'VKN' },
  { code: 'TV', name: 'Tuvalu', tax_label: 'Tax ID' },
  { code: 'UA', name: 'Ucrania', tax_label: 'EDRPOU' },
  { code: 'UG', name: 'Uganda', tax_label: 'TIN' },
  { code: 'UZ', name: 'Uzbekistan', tax_label: 'INN' },
  { code: 'VU', name: 'Vanuatu', tax_label: 'TIN' },
  { code: 'VN', name: 'Vietnam', tax_label: 'MST' },
  { code: 'WF', name: 'Wallis y Futuna', tax_label: 'Tax ID' },
  { code: 'YE', name: 'Yemen', tax_label: 'TIN' },
  { code: 'DJ', name: 'Yibuti', tax_label: 'NIF' },
  { code: 'ZM', name: 'Zambia', tax_label: 'TPIN' },
  { code: 'ZW', name: 'Zimbabue', tax_label: 'TIN' },

  // ---- Territorios y dependencias adicionales ------------------------------
  { code: 'AW', name: 'Aruba', tax_label: 'Tax ID' },
  { code: 'AI', name: 'Anguila', tax_label: 'Tax ID' },
  { code: 'AQ', name: 'Antartida', tax_label: 'Tax ID' },
  { code: 'BV', name: 'Isla Bouvet', tax_label: 'Tax ID' },
  { code: 'VG', name: 'Islas Virgenes Britanicas', tax_label: 'Tax ID' },
  { code: 'VI', name: 'Islas Virgenes de los Estados Unidos', tax_label: 'EIN' },
  { code: 'KY', name: 'Islas Caiman', tax_label: 'Tax ID' },
  { code: 'CK', name: 'Islas Cook', tax_label: 'Tax ID' },
  { code: 'FK', name: 'Islas Malvinas', tax_label: 'Tax ID' },
  { code: 'FO', name: 'Islas Feroe', tax_label: 'Tax ID' },
  { code: 'HM', name: 'Islas Heard y McDonald', tax_label: 'Tax ID' },
  { code: 'MP', name: 'Islas Marianas del Norte', tax_label: 'EIN' },
  { code: 'NU', name: 'Niue', tax_label: 'Tax ID' },
  { code: 'NF', name: 'Isla Norfolk', tax_label: 'ABN' },
  { code: 'TC', name: 'Islas Turcas y Caicos', tax_label: 'Tax ID' },
  { code: 'UM', name: 'Islas Menores Alejadas de los Estados Unidos', tax_label: 'Tax ID' },
  { code: 'AX', name: 'Islas Aland', tax_label: 'Y-tunnus' },
  { code: 'CC', name: 'Islas Cocos', tax_label: 'ABN' },
  { code: 'CX', name: 'Isla de Navidad', tax_label: 'ABN' },
  { code: 'CW', name: 'Curazao', tax_label: 'Tax ID' },
  { code: 'EH', name: 'Sahara Occidental', tax_label: 'Tax ID' },
  { code: 'GG', name: 'Guernsey', tax_label: 'Tax ID' },
  { code: 'GI', name: 'Gibraltar', tax_label: 'Tax ID' },
  { code: 'HK', name: 'Hong Kong', tax_label: 'BRN' },
  { code: 'IM', name: 'Isla de Man', tax_label: 'Tax ID' },
  { code: 'JE', name: 'Jersey', tax_label: 'Tax ID' },
  { code: 'MO', name: 'Macao', tax_label: 'Tax ID' },
  { code: 'PF', name: 'Polinesia Francesa', tax_label: 'Tax ID' },
  { code: 'GS', name: 'Islas Georgia del Sur y Sandwich del Sur', tax_label: 'Tax ID' },
  { code: 'SJ', name: 'Svalbard y Jan Mayen', tax_label: 'Tax ID' },
  { code: 'SH', name: 'Santa Elena, Ascension y Tristan de Acuna', tax_label: 'Tax ID' },
  { code: 'BQ', name: 'Bonaire, San Eustaquio y Saba', tax_label: 'Tax ID' },
  { code: 'PN', name: 'Islas Pitcairn', tax_label: 'Tax ID' },
];
