version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: enfoque_user
      POSTGRES_PASSWORD: enfoque_password
      POSTGRES_DB: enfoque365
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
