"""Add memorandum_ia

Revision ID: f5395f1cbf5e
Revises: 0003
Create Date: 2026-06-19 18:43:34.376439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5395f1cbf5e'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planes_estrategicos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('memorandum_ia', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('planes_estrategicos', schema=None) as batch_op:
        batch_op.drop_column('memorandum_ia')

    # ### end Alembic commands ###
